[project]
name = "pytodo"
version = "0.1.0"
description = "Simple Task Manager"
requires-python = ">=3.13"
dependencies = [
    "freesimplegui>=5.2.0.post1",
    "platformdirs>=4.3.8",
    "streamlit>=1.47.1",
]
